[build-system]
requires = ["setuptools>=61.0", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "intervalues"
authors = [
  { name="Bert de Bruijn", email="lpdebruijn@gmail.com" },
]
description = "Efficient combining of intervals of numbers."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["intervals", "continuous", "set", "counter"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[project.urls]
Homepage = "https://gitlab.com/bert.debruijn/intervalues"
Issues = "https://gitlab.com/bert.debruijn/intervalues/-/issues"

[tool.ruff]
target-version = "py310"
line-length = 127

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

[tool.mypy]
python_version = "3.10"
mypy_path = "stubs"

[tool.setuptools.packages.find]
include = ["intervalues*"]

[tool.setuptools.package-data]
intervalues = ["py.typed"]

[[tool.setuptools-rust.ext-modules]]
# Private Rust extension module to be nested into the Python package
target = "intervalues_pyrust"  # The last part of the name (e.g. "_lib") has to match lib.name in Cargo.toml,
                             # but you can add a prefix to nest it inside of a Python package.
path = "rust/Cargo.toml"      # Default value, can be omitted
binding = "PyO3"         # Default value, can be omitted